source_host: localhost
source_port: 5432
source_database: lakemover_test
source_username: postgres
source_password: root

lakebase_host: ep-hidden-lab-d8xz9gfs.database.us-east-2.cloud.databricks.com
lakebase_port: 5432
lakebase_database: databricks_postgres
lakebase_username: arjun.k.rana@v4c.ai
lakebase_password: eyJraWQiOiI2NDZiZWZkNGY5NjYwMTdiNjk1MjRjOTRlMjcxNzljY2YyZmRlZDU1ZGJiMzQ5N2UwZjEwM2EwMzljZjI2ODU3IiwidHlwIjoiYXQrand0IiwiYWxnIjoiUlMyNTYifQ.eyJjbGllbnRfaWQiOiJkYXRhYnJpY2tzLXNlc3Npb24iLCJzY29wZSI6ImlhbS5jdXJyZW50LXVzZXI6cmVhZCBpYW0uZ3JvdXBzOnJlYWQgaWFtLnNlcnZpY2UtcHJpbmNpcGFsczpyZWFkIGlhbS51c2VyczpyZWFkIiwiaWRtIjoiRUFBPSIsImlzcyI6Imh0dHBzOi8vZGJjLTIwMmY0ODA4LTE3NTQuY2xvdWQuZGF0YWJyaWNrcy5jb20vb2lkYyIsImF1ZCI6Ijg0MjQ0NjEwODU5Mjg5NSIsInN1YiI6ImFyanVuLmsucmFuYUB2NGMuYWkiLCJpYXQiOjE3NzkxNzYyODksImV4cCI6MTc3OTE3OTg4OSwianRpIjoiNjk3Nzg5ZmYtMjZlMy00MzQ2LWFlZWEtNGNjMjhiYmViMjNkIn0.gUYiD33a1dvLyCL8VTq5pOp2yCRD9ztHdWt5HtUSaNGcwaPlcl_TrxiYWBEp2D1YXQ6SkqZbx-Z6upzuPTA4d9yRGyXydDv3lvT5QqIraA_PZ9l_C5tibmdW2KeROKHoq4pcdt_c9hnOrb0YvUrck2Un6Tu6O6l0azPPw9t75GwuhexvtJGE4DH9iMKdmvHLBuO67i8sIBNOZUUpJxV0GS8yREOWzyfsHkey6srruBXbm-qV-lwPvlBXzFPyc62rvwhil6QnyNJq-66XnUvUYtA8eY8Aod_lnsvkaoEYQHuqCr-1qdh1dvcf1ayciXXJ69NKvHWFAsncAiO0d0v7GQ
lakebase_sslmode: require